chain_client:
  chain_id: ahqb001
  org_id: online.zust
  user_key_file_path: ./crypto-config/online.zust/user/anheqiaobei/anheqiaobei.tls.key
  user_crt_file_path: ./crypto-config/online.zust/user/anheqiaobei/anheqiaobei.tls.crt
  user_sign_key_file_path: ./crypto-config/online.zust/user/anheqiaobei/anheqiaobei.sign.key
  user_sign_crt_file_path: ./crypto-config/online.zust/user/anheqiaobei/anheqiaobei.sign.crt
  retry_limit: 10
  retry_interval: 500
  nodes:
  - node_addr: 114.134.188.229:12001
    conn_cnt: 10
    enable_tls: true
    trust_root_paths:
    - ./crypto-config/online.zust/ca
    tls_host_name: chainmaker.org
  archive:
    type: mysql
    dest: root:RrOoOoTt!@#123.:localhost:33060
    secret_key: xxx
  rpc_client:
    max_receive_message_size: 16

